"""Add foreign key constraint to comments

Revision ID: 07cbbbc1f7e1
Revises: 8b97ba8df45b
Create Date: 2018-06-03 19:33:07.560764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cbbbc1f7e1'
down_revision = '8b97ba8df45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'comment_count')
    op.drop_column('pull_requests', 'ack_comment_count')
    # ### end Alembic commands ###
    op.create_foreign_key('comments_pull_request_id_fkey',
                          'comments', 'pull_requests',
                          ['pull_request_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('ack_comment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pull_requests', sa.Column('comment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('comments_pull_request_id_fkey')
    # ### end Alembic commands ###
