"""First version

Revision ID: 154063888264
Revises: 
Create Date: 2018-06-03 12:15:28.557165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154063888264'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
