"""add last_commit_pushed_date field

Revision ID: 1efa9375e67b
Revises: ac1f880ead3a
Create Date: 2019-06-16 22:04:14.424798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efa9375e67b'
down_revision = 'ac1f880ead3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('last_commit_pushed_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'last_commit_pushed_date')
    # ### end Alembic commands ###
