"""Change polling model

Revision ID: 20c45fff9ccb
Revises: 1efa9375e67b
Create Date: 2020-07-05 16:12:47.521137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20c45fff9ccb'
down_revision = '1efa9375e67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_polling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('polling')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polling',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_event', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_open_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_full_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='polling_pkey')
    )
    op.drop_table('service_polling')
    # ### end Alembic commands ###
