"""Add comments url constraint

Revision ID: 330754eb6c0e
Revises: 70c1ac4a3ac2
Create Date: 2020-10-22 17:32:11.209176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330754eb6c0e'
down_revision = '70c1ac4a3ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comments', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='unique')
    # ### end Alembic commands ###
