"""Update pull requests table repositories fk

Revision ID: 4b95bea30431
Revises: 58c75e769b5c
Create Date: 2020-11-08 16:26:56.831551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b95bea30431'
down_revision = '330754eb6c0e'
branch_labels = None
depends_on = None


def upgrade():
    # Change primary key type
    op.alter_column('pull_requests', 'repository_id', existing_type=sa.Integer, type_=sa.VARCHAR)
    op.alter_column('users_repositories', 'repository_id', existing_type=sa.Integer, type_=sa.VARCHAR)
    # Re-create the primary key constraint
    # op.create_primary_key('repositories_pkey', 'repositories', ['id'])
    # Re-create the foreign key constraint
    # op.create_foreign_key(None, 'users_repositories', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
