"""Change repo ID to string

Revision ID: 58c75e769b5c
Revises: ca7ce933e8c5
Create Date: 2020-11-08 13:57:12.349260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c75e769b5c'
down_revision = 'ca7ce933e8c5'
branch_labels = None
depends_on = None


def upgrade():
    # Drop primary key constraint. Note the CASCASE clause - this deletes the foreign key constraint.
    op.execute('ALTER TABLE repositories DROP CONSTRAINT repositories_pkey CASCADE')
    # Change primary key type
    op.alter_column('repositories', 'id', existing_type=sa.Integer, type_=sa.VARCHAR)
    op.alter_column('users_repositories', 'repository_id', existing_type=sa.Integer, type_=sa.VARCHAR)
    # Re-create the primary key constraint
    op.create_primary_key('repositories_pkey', 'repositories', ['id'])
    # Re-create the foreign key constraint
    op.create_foreign_key(None, 'users_repositories', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
