"""add a review count cache

Revision ID: 7bb40ce4cd80
Revises: 07cbbbc1f7e1
Create Date: 2018-06-04 08:57:09.074737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb40ce4cd80'
down_revision = '07cbbbc1f7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('review_decisions_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'review_decisions_count')
    # ### end Alembic commands ###
