"""Add more review counts

Revision ID: 92a9e8f5c134
Revises: 4b95bea30431
Create Date: 2022-11-25 21:36:08.969416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92a9e8f5c134'
down_revision = '4b95bea30431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('stale_tested_ack_count', sa.Integer(), nullable=True))
    op.add_column('pull_requests', sa.Column('fresh_tested_ack_count', sa.Integer(), nullable=True))
    op.add_column('pull_requests', sa.Column('untested_ack_count', sa.Integer(), nullable=True))
    op.add_column('pull_requests', sa.Column('concept_ack_count', sa.Integer(), nullable=True))
    op.add_column('pull_requests', sa.Column('nack_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'nack_count')
    op.drop_column('pull_requests', 'concept_ack_count')
    op.drop_column('pull_requests', 'untested_ack_count')
    op.drop_column('pull_requests', 'fresh_tested_ack_count')
    op.drop_column('pull_requests', 'stale_tested_ack_count')
    # ### end Alembic commands ###
