"""add high priority fields

Revision ID: ac1f880ead3a
Revises: 7bb40ce4cd80
Create Date: 2019-06-11 20:16:46.699366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1f880ead3a'
down_revision = '7bb40ce4cd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id')
    )
    op.add_column('pull_requests', sa.Column('added_to_high_priority', sa.DateTime(), nullable=True))
    op.add_column('pull_requests', sa.Column('removed_from_high_priority', sa.DateTime(), nullable=True))
    op.add_column('pull_requests', sa.Column('toot_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'pull_requests', ['toot_id'])
    op.drop_column('pull_requests', 'head_repository_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('head_repository_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pull_requests', type_='unique')
    op.drop_column('pull_requests', 'toot_id')
    op.drop_column('pull_requests', 'removed_from_high_priority')
    op.drop_column('pull_requests', 'added_to_high_priority')
    op.drop_table('toots')
    # ### end Alembic commands ###
