"""Add fields to repositories table

Revision ID: ca7ce933e8c5
Revises: 57d7591b8ce1
Create Date: 2020-11-08 12:58:40.473095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7ce933e8c5'
down_revision = '57d7591b8ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('repositories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'updated_at')
    op.drop_column('repositories', 'description')
    op.drop_column('repositories', 'created_at')
    # ### end Alembic commands ###
