"""Add btcpay

Revision ID: e9766272137f
Revises: c2a262fda8d4
Create Date: 2020-07-11 15:52:15.147683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9766272137f'
down_revision = 'c2a262fda8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bounty_id', sa.String(), nullable=False),
    sa.Column('recipient_user_id', sa.String(), nullable=True),
    sa.Column('payer_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bounties', sa.Column('payer_user_id', sa.String(), nullable=True))
    op.add_column('bounties', sa.Column('recipient_user_id', sa.String(), nullable=True))
    op.alter_column('bounties', 'pull_request_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'bounties', 'users', ['recipient_user_id'], ['id'])
    op.create_foreign_key(None, 'bounties', 'users', ['payer_user_id'], ['id'])
    op.drop_column('bounties', 'creator_id')
    op.add_column('users', sa.Column('btcpay_client', sa.PickleType(), nullable=True))
    op.add_column('users', sa.Column('btcpay_host', sa.String(), nullable=True))
    op.add_column('users', sa.Column('btcpay_pairing_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'btcpay_pairing_code')
    op.drop_column('users', 'btcpay_host')
    op.drop_column('users', 'btcpay_client')
    op.add_column('bounties', sa.Column('creator_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bounties', type_='foreignkey')
    op.drop_constraint(None, 'bounties', type_='foreignkey')
    op.alter_column('bounties', 'pull_request_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bounties', 'recipient_user_id')
    op.drop_column('bounties', 'payer_user_id')
    op.drop_table('invoices')
    # ### end Alembic commands ###
