"""Remove last_commit_state_description column

Revision ID: fb7ce3a7f472
Revises: 92a9e8f5c134
Create Date: 2022-11-26 11:08:23.038437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb7ce3a7f472'
down_revision = '92a9e8f5c134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'last_commit_state_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('last_commit_state_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
